@token = 58804eee4348eb456603
POST http://localhost:8080/reservation
Authorization: {{token}}
Content-Type: application/json

{
    "user": "user1",
    "startDate": "startDate",
    "endDate":"endDate",
    "room": "someRoom"
}
###

GET http://localhost:8080/reservation/25783464194ef53fe9ad
Authorization: {{token}}
###

GET http://localhost:8080/reservation/all
Authorization: {{token}}
###

PUT http://localhost:8080/reservation/25783464194ef53fe9ad
Authorization: {{token}}
Content-Type: application/json

{
    "room": "someOtherRoom",
    "user": "user2"

}
###